### ISSUE TITLE
Add visual feedback on keyboard focus

### ISSUE THREAD

**Issue by johnslipper** [HosseinShabani/svelte-checkbox#5]
Nice slick animations! When I tab to it using the keyboard I can trigger the input as normal with the spacebar, but there is no visual feedback to indicate this to the user. Suggest using the old ["checkbox hack"](https://css-tricks.com/the-checkbox-hack/) to change the checkbox SVG styling when the input element is focused. Something like:

```css
.checkbox input:focus ~ .checkbox__svg {
    box-shadow: 0 0 0 2px blue;
    border-radius: 0.6em;
}
```
